// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsSaR-MqX9Rf_PvYX3mI2d463RlVmm020',
    appId: '1:509667905502:web:950d3474117c1439c7d74f',
    messagingSenderId: '509667905502',
    projectId: 'chatapp-a1eff',
    authDomain: 'chatapp-a1eff.firebaseapp.com',
    storageBucket: 'chatapp-a1eff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfibVu1r4F6zoPBva432yDNtvqrtVxzBA',
    appId: '1:509667905502:android:7c6a346afb7d2616c7d74f',
    messagingSenderId: '509667905502',
    projectId: 'chatapp-a1eff',
    storageBucket: 'chatapp-a1eff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiwRj6fLe2uHMhZM-p51gBtkuBw5otmZg',
    appId: '1:509667905502:ios:f3ef8e717ec82897c7d74f',
    messagingSenderId: '509667905502',
    projectId: 'chatapp-a1eff',
    storageBucket: 'chatapp-a1eff.appspot.com',
    iosBundleId: 'com.example.chatAppFirebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiwRj6fLe2uHMhZM-p51gBtkuBw5otmZg',
    appId: '1:509667905502:ios:8f9f185a57a2a7e7c7d74f',
    messagingSenderId: '509667905502',
    projectId: 'chatapp-a1eff',
    storageBucket: 'chatapp-a1eff.appspot.com',
    iosBundleId: 'com.example.chatAppFirebaseTutorial.RunnerTests',
  );
}
